// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwpijqpptgpphxxhtlsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3cGlqcXBwdGdwcGh4eGh0bHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0ODA3NTYsImV4cCI6MjA1MzA1Njc1Nn0.rS9CVU3yGufiDZRBeHvRUzDPwQktbUqZWo5iPcM4z5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);